---
title: "Полевые экспедиции Космопоиска / Kosmopoisk Field Deployments"
---
mindmap
  root((Медведицкая гряда<br/>Medveditskaya Gryada<br/>1982-2014<br/>50 экспедиций / expeditions<br/>906 участников / participants<br/>17 landing sites))
    Molebka
      Молёбка
      Perm region anomaly zone
    Dalnegorsk
      Дальнегорск
      1986 crash site / место крушения
    Tunguska
      Тунгуска
      1908 event re-investigations
    Arkaim
      Аркаим
      Bronze Age site / бронзовый век
    Sasovo
      Сасово
      1991 crater / воронка
    Chertovo Logovo
      Чёртово Логово
      anomaly / аномалия
    Pereslavl
      Переславль
      anomaly / аномалия
    MG-2002 deployment
      Ловондатр-7 field test
      2002-06-20: +12 min UFO
      2002-07-02: +114 min UFO
    MG-1998 anomaly
      1998-08-08
      +5 h clock jump<br/>скачок часов +5 ч
    Поляна сухостоя
      Dead-tree clearing
      3-5 min time lag<br/>отставание времени 3-5 мин
